version: '3'

services:
  ppm-db:
    container_name: ppm-db
    image: postgres:12.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ppm-db-data:/var/lib/postgresql/data

  ppm-api:
    container_name: ppm-api
    build: .
    command: python manage.py runserver 0.0.0.0:8003
    volumes:
      - .:/product_price_manager
    ports:
      - "8003:8003"
    depends_on:
      - ppm-db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    entrypoint: /entrypoint.sh
    env_file:
      - .env

volumes:
  ppm-db-data:
